# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-23 07:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('note_api', '0002_note_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='creater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
