# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-24 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_api', '0004_remove_note_creater'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='creater',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
