# Generated by Django 2.1.7 on 2019-02-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_api', '0006_auto_20190224_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
